### ISSUE TITLE
20211120課題での質問

### ISSUE THREAD

**Issue by yokikoshimizu** [yokikoshimizu/20211120_task#2]
@SatakeYusuke19920527 
お疲れ様です！
先日の講義の宿題についてはこのissueで質問させていただきます。

取り急ぎ、現在作成した段階までのコードをプッシュしました！
今躓いているのは、ヘッダー下に表示されているメニュー部分の配置についてです。

①ulタグ（<ul class></ul>）で作成したメニュー（画像ファイル含む）をdisplay: flexで横並びにする
②<ul class>を親要素としてその中に子要素を作成
③子要素にdisplay: flex及びjustify-content: space-betweenを使用して、①で横並びにしたメニューを均等配置

という手順でレイアウトを作成しようとしているのですが、③の段階でjustify-content: space-betweenがうまく効きません…
理想ではヘッダーと同じ幅の両端まで均等に広がってほしいのですが…

子要素にはmarginをつけていないので、私自身で調べた限りでは原因がいまいちわかりませんでした。。。

こちらについてヒントをいただけますと幸いです。

よろしくお願いいたします！

**Comment by SatakeYusuke19920527** [comment]
```
<ul>
 <li></li>
</ul>
```
の構成になっていると思いますが、ulに
display: flex
justyfy-content: space-between;
をつけてみてください！

**Comment by SatakeYusuke19920527** [comment]
解決できたら、クローズをお願いします！

**Comment by yokikoshimizu** [comment]
@SatakeYusuke19920527 
お疲れ様です！
先日はアドバイスいただきありがとうございました！

本課題、一通りレイアウトのコーディングを行いましたのでご確認ください！
上手くいかなかった（追加アドバイスをいただきたい）点は以下です。

■\←半角バックスラッシュが￥マークで表示されてしまう（調べて&#92;などのコードを打ってみましたが反映されませんでした…）
■フッター部分の段落の隙間の埋め方を知りたい

他にも「うまくいったけどなんでやろ…？」という部分が何点かあるので、また次回の講義時に確認させていただきたく存じます。

よろしくお願いいたします！

**Comment by SatakeYusuke19920527** [comment]
以下のサイトを参考にしてください！
https://qumeru.com/magazine/460

解決できると思います！

**Comment by SatakeYusuke19920527** [comment]
解決できたら、クローズをお願いします！

**Comment by yokikoshimizu** [comment]
@SatakeYusuke19920527 
お疲れ様です！

先日の課題の続きと修正、追加質問を記載します！

【課題・修正点】
■お問い合わせフォーム、完成しました
■バックスラッシュの記載ができました
■画像を全て相対パスにしました

【追加質問】
■お問い合わせフォーム一番下の送信ボタンがずれています。ディベロッパーツールで見てみると左側に余白があるのですが、中央に寄せるにはどうコーディングすればよいでしょうか？

■車の写真部分（moddleという名前でくるんでいます）のレイアウトが難しく…最初は「月々14,000円」の部分を右揃えにしようと思っていじっていましたが、これもウィンドウのサイズを変更すると色々とおかしくなりました。フルウィンドウではmarginを左にとって誤魔化していましたが、これもどう解決すればよいでしょうか？

■バックスラッシュのフォントサイズを変更したいのですが、この場合htmlのどの部分にサイズ指定のコードを書けばよいでしょうか？（※現状<font size></font>で包んでいますがきいていません…）


以上、ご確認＆ご回答のほど、よろしくお願いいたします！

**Comment by SatakeYusuke19920527** [comment]
【追加質問】
■お問い合わせフォーム一番下の送信ボタンがずれています。ディベロッパーツールで見てみると左側に余白があるのですが、中央に寄せるにはどうコーディングすればよいでしょうか？
- 完了

■車の写真部分（moddleという名前でくるんでいます）のレイアウトが難しく…最初は「月々14,000円」の部分を右揃えにしようと思っていじっていましたが、これもウィンドウのサイズを変更すると色々とおかしくなりました。フルウィンドウではmarginを左にとって誤魔化していましたが、これもどう解決すればよいでしょうか？
- 修正

■バックスラッシュのフォントサイズを変更したいのですが、この場合htmlのどの部分にサイズ指定のコードを書けばよいでしょうか？（※現状で包んでいますがきいていません…）
- 完了

**Comment by yokikoshimizu** [comment]
@SatakeYusuke19920527 
おつかれさまです！

こちらの修正も完了しました。
因数分解とまではいきませんが不要なコードを数点消してみたので、別イシューの課題と共に、プッシュしたコードをご確認ください！

ありがとうございました！
